### ISSUE TITLE
Include test files in hackage tarball

### ISSUE THREAD

**Issue by DanBurton** [riak-haskell-client/riak-haskell-client#100]
There was a failure on the stackage build server when attempting to build the test suite for `riak-1.1.2.2`.

```
[2 of 6] Compiling Utils            ( tests/Utils.hs, dist/build/test/test-tmp/Utils.o )

tests/Utils.hs:33:13: error:
    • YAML exception:
Yaml file not found: tests/test.yaml
    • In the Template Haskell splice $$(decodeFile "tests/test.yaml")
      In the expression: $$(decodeFile "tests/test.yaml")
      In an equation for ‘config’:
          config = $$(decodeFile "tests/test.yaml")
   |
33 | config = $$(decodeFile "tests/test.yaml")
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

How I reproduced locally:

```bash
$ stack unpack riak-1.1.2.2 && cd riak-1.1.2.2
$ vi stack.yaml # add the following stack.yaml file
$ stack test
```

```yaml
# stack.yaml
resolver: nightly-2017-12-07
extra-deps:
- riak-protobuf-0.23.0.0
```

**Comment by DanBurton** [comment]
I've marked riak's test suite in stackage as an expected failure. Feel free to open a PR reverting this commit once the issue is addressed. https://github.com/fpco/stackage/commit/bee40b75c4871a1f868b45deb933ae35e721f315

**Comment by tmcgilchrist** [comment]
Fix in http://hackage.haskell.org/package/riak-1.1.2.3

**Comment by juhp** [comment]
(Just noting that a riak server would have to be setup in the Stackage docker to get the testsuite to pass.)
