### ISSUE TITLE
riak-protobuf-0.23.0.0 doesn't compile with protocol-buffers 2.4.12

### ISSUE THREAD

**Issue by tmcgilchrist** [riak-haskell-client/riak-haskell-client#115]
See the stack issue https://github.com/commercialhaskell/stackage/issues/4167

**Comment by tmcgilchrist** [comment]
@mitchellwrosen Ideally we'd get this issue sorted and back into stockage, before we include the work you're doing on https://github.com/riak-haskell-client/riak-haskell-client/pull/119.

**Comment by tmcgilchrist** [comment]
I have a working version of this https://github.com/riak-haskell-client/riak-haskell-client/pull/114. That includes a bump to `riak` `riak-protobuf` and `riak-protobuf-lens` so they continue working with the latest `protocol-buffers` version. See https://github.com/riak-haskell-client/riak-haskell-client/issues/115. 

After that we can bump the versions again to include the work https://github.com/riak-haskell-client/riak-haskell-client/pull/119 which switches out `protocol-buffers` for ` proto-lens` and makes a major version change and possibly breaks API compatibility.

Are you ok with that process @mitchellwrosen ?

**Comment by mitchellwrosen** [comment]
Sounds good @tmcgilchrist

**Comment by mitchellwrosen** [comment]
@tmcgilchrist Just waiting on #114 to get merged, then I'll rebase #119 on top. No rush though.

**Comment by tmcgilchrist** [comment]
No worries, thanks for the reminder. I should find some time this weekend
to do it.

**Comment by tmcgilchrist** [comment]
Released as:
https://hackage.haskell.org/package/riak-1.1.2.6
https://hackage.haskell.org/package/riak-protobuf-0.24.0.0
https://hackage.haskell.org/package/riak-protobuf-lens-0.24.0.0
