### ISSUE TITLE
Proposal for `riak-protobuf`: use `proto-lens`

### ISSUE THREAD

**Issue by mitchellwrosen** [riak-haskell-client/riak-haskell-client#118]
In https://github.com/mitchellwrosen/riak2 I tried out the `proto-lens` library, it's nicer than `protocol-buffers` in my opinion. I propose we move `riak-protobuf` over to using it, and bump it to `1.0.0`. I also propose we simultaneously simplify the protobuf generation by just sticking with Riak's protobuf naming mechanism (e.g. don't bother converting `RpbGetReq` to `GetReq`).

Overall consequences:

1. Breaking change to `riak-protobuf`, wherein not only the type names change, also they no longer have exported record accessors. Instead, lenses are generated for every record field.
2. Everything type and function can be exported from one module. I propose `Data.Riak.Proto` (as the use of `Network.*` for this library has always struck me as odd).
3. `riak-protobuf-lens` can be deprecated, `proto-lens` covers this.

I'm happy to implement this, and also do the necessary refactoring to `riak` itself (if that is desired). Let me know what you all think.

**Comment by tmcgilchrist** [comment]
Sounds good. Interested to see how it turns out.

**Comment by mitchellwrosen** [comment]
#119
