### ISSUE TITLE
deploy latest and greatest to hackage

### ISSUE THREAD

**Issue by choyuri** [riak-haskell-client/riak-haskell-client#124]
Could we please get  updated packages uploaded to hackage :)

**Comment by tmcgilchrist** [comment]
Published as:
https://hackage.haskell.org/package/riak-1.2.0.0
https://hackage.haskell.org/package/riak-protobuf-0.25.0.0
https://hackage.haskell.org/package/riak-protobuf-lens-0.25.0.0

Let me know if there are issues.
