### ISSUE TITLE
Question - Ability to write / query RiakTS

### ISSUE THREAD

**Issue by mankyKitty** [riak-haskell-client/riak-haskell-client#75]
Greetings,

Curious to know if it's possible to make this package support writing and querying RiakTS? Either through use of some internal functions or using the riak-protobuf API ? 

Happy to throw together a PR or new package (using protobuf api), but just a bit lost as to where to begin.

We're just getting our feet wet with RiakTS so my apologies if I've just missed something obvious in the docs.

**Comment by tmcgilchrist** [comment]
I have not used RiakTS. I need to do some reading on what it actually is and how it differs from plain Riak. Let me have a look and I'll comment on here.

**Comment by mankyKitty** [comment]
We've got a simple HTTP API integration going at the moment, it's pretty braindead. A Basho dev on IRC said that the RiakTS protobuf API is substantially different as they make allowances for bulk inputs etc, and the resolving doesn't quite work the same way.

I couldn't find any docs on the TS specific protobuf API though and I haven't heard back from them about it. Could just be poor search-fu on my part...

**Comment by thierry-b** [comment]
the protobuf for riak_ts is located here:
https://raw.githubusercontent.com/basho/riak_pb/cb15cc4770f3748289ba56245d62b1c0d07c33f7/src/riak_ts.proto
