### ISSUE TITLE
Remove user-specified Typeable instances

### ISSUE THREAD

**Issue by DanBurton** [riak-haskell-client/riak-haskell-client#98]
Build failure with riak-protobuf-0.22.0.0 using ghc 8.2.2, as seen on the stackage build server:

```
[36 of 74] Compiling Network.Riak.Protocol.MapOp[boot] ( src/Network/Riak/Protocol/MapOp.hs-boot, dist/build/Network/Riak/Protocol/MapOp.o-boot )

src/Network/Riak/Protocol/MapOp.hs-boot:19:1: error:
    • Class ‘Prelude'.Typeable’ does not support user-specified instances
    • In the instance declaration for ‘Prelude'.Typeable MapOp’
   |
19 | instance Prelude'.Typeable MapOp
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by tmcgilchrist** [comment]
Right, I have this fixed on master. Will release a new version.

**Comment by tmcgilchrist** [comment]
How can I test out the new versions @DanBurton 
riak-1.1.2.2
riak-protobuf-0.23.0.0

They are (or should be) both building with 8.2.2 now.

**Comment by DanBurton** [comment]
What I usually do to test things on my local machine is:

```
$ stack unpack riak-protobuf-0.23.0.0 && cd riak-protobuf-0.23.0.0
$ stack init --resolver nightly-2017-12-07
$ stack test
```

(Which I just did, and it looks like it works. 👍 )

The recommendation that you can find on [stackage/MAINTAINERS.md](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package) is a little more meticulous:

```
# Build from the tarball on Hackage to check for missing files
$ stack unpack yourpackage && cd yourpackage-*
# Generate a pristine stack.yaml, adding any missing extra-deps
$ rm -f stack.yaml && stack init --resolver nightly --solver
# Build, generate docs, test, and build benchmarks
$ stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
```

**Comment by tmcgilchrist** [comment]
Thanks for the explanation, I’m not a frequent stack user so don’t know all
the tricks.
